openapi: 3.0.0
info:
  title: Argent Bank Transaction API
  description: API pour gérer les transactions des utilisateurs d'Argent Bank
  version: 1.0.0
servers:
  - url: https://api.argentbank.com/v1
paths:
  /transactions:
    get:
      summary: Récupérer les transactions de l'utilisateur
      description: Retourne toutes les transactions de l'utilisateur pour le mois en cours, groupées par compte
      parameters:
        - in: query
          name: month
          schema:
            type: string
          required: false
          description: Mois pour lequel récupérer les transactions (format YYYY-MM)
        - in: query
          name: accountId
          schema:
            type: string
          required: false
          description: ID du compte spécifique pour filtrer les transactions
      responses:
        '200':
          description: Liste des transactions récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Non autorisé
        '404':
          description: Aucune transaction trouvée

  /transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID de la transaction
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Non autorisé
        '404':
          description: Transaction non trouvée

    put:
      summary: Modifier les informations d'une transaction
      description: Permet de modifier les informations d'une transaction existante
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID de la transaction à modifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Transaction mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Données invalides fournies
        '401':
          description: Non autorisé
        '404':
          description: Transaction non trouvée

    delete:
      summary: Supprimer une transaction
      description: Permet de supprimer une transaction existante
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID de la transaction à supprimer
      responses:
        '204':
          description: Transaction supprimée avec succès
        '401':
          description: Non autorisé
        '404':
          description: Transaction non trouvée

  /transactions/new:
    post:
      summary: Ajouter une nouvelle transaction
      description: Permet d'ajouter une nouvelle transaction pour l'utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTransaction'
      responses:
        '201':
          description: Transaction créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Données invalides fournies
        '401':
          description: Non autorisé

components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        accountId:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        amount:
          type: number
        balance:
          type: number
        type:
          type: string
          enum: [debit, credit]
        category:
          type: string
        notes:
          type: string

    TransactionUpdate:
      type: object
      properties:
        description:
          type: string
        category:
          type: string
        notes:
          type: string

    NewTransaction:
      type: object
      required:
        - accountId
        - date
        - description
        - amount
        - type
      properties:
        accountId:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        amount:
          type: number
        type:
          type: string
          enum: [debit, credit]
        category:
          type: string
        notes:
          type: string