openapi: 3.0.0
info:
  title: Argent Bank Transaction API
  description: API pour gérer les transactions des utilisateurs d'Argent Bank
  version: 1.0.0
servers:
  - url: https://api.argentbank.com/v1

paths:
  /user/{userId}/transactions:
    get:
      summary: Récupérer les transactions de l'utilisateur pour le mois en cours
      description: Retourne toutes les transactions de l'utilisateur pour le mois en cours, groupées par compte
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID de l'utilisateur
        - in: query
          name: accountId
          schema:
            type: string
          required: false
          description: ID du compte spécifique pour filtrer les transactions (optionnel)
      responses:
        '200':
          description: Liste des transactions récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Non autorisé
        '404':
          description: Aucune transaction trouvée

  /user/{userId}/transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction spécifique
      description: Retourne les détails supplémentaires d'une transaction spécifique
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID de l'utilisateur
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID de la transaction
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetails'
        '401':
          description: Non autorisé
        '404':
          description: Transaction non trouvée

    put:
      summary: Modifier ou supprimer les informations supplémentaires d'une transaction
      description: Permet de modifier, ajouter ou supprimer des informations supplémentaires d'une transaction existante
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID de l'utilisateur
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: ID de la transaction à modifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Transaction mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetails'
        '400':
          description: Données invalides fournies
        '401':
          description: Non autorisé
        '404':
          description: Transaction non trouvée

components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        amount:
          type: number
        type:
          type: string
          enum: [credit, debit]
        category:
          type: string

    TransactionDetails:
      allOf:
        - $ref: '#/components/schemas/Transaction'
        - type: object
          properties:
            notes:
              type: string
            tags:
              type: array
              items:
                type: string

    TransactionUpdate:
      type: object
      properties:
        category:
          type: string
        notes:
          type: string
        tags:
          type: array
          items:
            type: string
      description: Pour supprimer les informations supplémentaires, envoyez des valeurs vides ou null pour les champs correspondants